/**
 * @file layout.tsx
 * @author Nexus Estates team
 * @description Layout principal da aplicação. Define a estrutura base de todas as páginas, 
 *              configurações de metadados, fontes, e envolve a aplicação com os provedores necessários (Clerk, Chat, View).
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/feedback/sonner-brutal";
import { ChatProvider } from "@/features/chat";
import { ViewProvider } from "@/providers/view-context";
import { ClerkProvider } from "@clerk/nextjs";

/**
 * Fonte principal, para textos, botões e menus (fornecida pela Geist).
 * Usada globalmente para garantir uma tipografia consistente e moderna.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * A fonte para código, números ou dados tabulares (fornecida pela Geist).
 * Garante que dados tabulares ou trechos de código fiquem alinhados.
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Metadata da aplicação para o cabeçalho do documento HTML (tags `<head>`).
 * Define o título e a descrição que aparecem no navegador e em motores de busca.
 */
export const metadata: Metadata = {
  title: "Nexus-Estates",
  description: "Generated by create next app",
};

/**
 * Componente de Layout do Root.
 * Este componente envolve todas as rotas da aplicação, injetando as fontes, 
 * os estilos globais e os provedores de estado globais.
 * 
 * @param {Object} props - Propriedades do componente de layout.
 * @param {React.ReactNode} props.children - O conteúdo ou página atual a ser renderizada.
 * @returns {JSX.Element} Estrutura base HTML da aplicação configurada.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clerkPublishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;
  const idp = (process.env.NEXT_PUBLIC_IDP ?? "clerk").toLowerCase();
  const enableClerk = Boolean(clerkPublishableKey) && idp === "clerk";

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
          {/* Componente para notificações globais (Toasts), definindo a posição no topo ao centro */}
          <Toaster position="top-center"/>

          <div className="min-h-screen">
            {/* Se o Clerk estiver ativado, envolve com ClerkProvider. Em ambos os casos, fornece o contexto de Chat e View */}
            {enableClerk ? (
              <ClerkProvider publishableKey={clerkPublishableKey}>
                <ChatProvider>
                  <ViewProvider>

                {/* Conteúdo da página atual sendo renderizada */}
                {children}
                  </ViewProvider>
                </ChatProvider>
              </ClerkProvider>
            ) : (
              <ChatProvider>
                <ViewProvider>{children}</ViewProvider>
              </ChatProvider>
            )}
          </div>

      </body>
    </html>
  );
}
