import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/feedback/sonner-brutal";
import { ChatProvider } from "@/features/chat/ChatProvider";
import {ViewProvider} from "@/features/view-context";

/**
 * Fonte principal, para textos, botões e menus (fornecida pela Geist)
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * A fonte para código, números ou dados tabulares (fornecida pela Geist)
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Metadata da aplicação para o cabeçajo do documento
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Componente de Layout do Root
 * Injeta fontes, estilos globais e providers
 * @param children - componetes filhas desta
 * @returns layout configurado para ser aplicado a um ficheiro page.tsx
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
          {/* define a postição das notificações Toasts */}
          <Toaster position="top-right"/>

          <div className="min-h-screen">
            {/* inicia o Provider do serviço de chat */}
            <ChatProvider>
                {/* inicia o Provider*/}
                <ViewProvider>

              {/* Conteodo da page.tsx desta pasta */}
              {children}
                </ViewProvider>
            </ChatProvider>
          </div>

      </body>
    </html>
  );
}
