CREATE SEQUENCE IF NOT EXISTS amenities_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS property_permissions_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE amenities
(
    id       BIGINT       NOT NULL,
    name     VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    CONSTRAINT pk_amenities PRIMARY KEY (id)
);

CREATE TABLE properties
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    city        VARCHAR(255)                            NOT NULL,
    address     VARCHAR(255)                            NOT NULL,
    base_price  DECIMAL(10, 2)                          NOT NULL,
    max_guests  INTEGER                                 NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_properties PRIMARY KEY (id)
);

CREATE TABLE property_permissions
(
    id           BIGINT       NOT NULL,
    property_id  BIGINT       NOT NULL,
    user_id      BIGINT       NOT NULL,
    access_level VARCHAR(255) NOT NULL,
    CONSTRAINT pk_property_permissions PRIMARY KEY (id)
);

ALTER TABLE amenities
    ADD CONSTRAINT uc_amenities_name UNIQUE (name);