CREATE SEQUENCE IF NOT EXISTS property_permissions_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE amenities
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     JSONB                                   NOT NULL,
    category VARCHAR(255)                            NOT NULL,
    icon     VARCHAR(255),
    CONSTRAINT pk_amenities PRIMARY KEY (id)
);

CREATE TABLE properties
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description JSONB,
    location    VARCHAR(255)                            NOT NULL,
    city        VARCHAR(255)                            NOT NULL,
    address     VARCHAR(255)                            NOT NULL,
    base_price  DECIMAL(10, 2)                          NOT NULL,
    max_guests  INTEGER                                 NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    image_url   VARCHAR(255),
    CONSTRAINT pk_properties PRIMARY KEY (id)
);

CREATE TABLE property_amenities
(
    amenity_id  BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    CONSTRAINT pk_property_amenities PRIMARY KEY (amenity_id, property_id)
);

CREATE TABLE property_permissions
(
    id           BIGINT       NOT NULL,
    property_id  BIGINT       NOT NULL,
    user_id      BIGINT       NOT NULL,
    access_level VARCHAR(255) NOT NULL,
    CONSTRAINT pk_property_permissions PRIMARY KEY (id)
);

CREATE TABLE seasonality_rules
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id    BIGINT                                  NOT NULL,
    start_date     date                                    NOT NULL,
    end_date       date                                    NOT NULL,
    price_modifier DECIMAL(5, 2)                           NOT NULL,
    day_of_week    VARCHAR(255),
    channel        VARCHAR(255),
    CONSTRAINT pk_seasonality_rules PRIMARY KEY (id)
);

ALTER TABLE seasonality_rules
    ADD CONSTRAINT FK_SEASONALITY_RULES_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

ALTER TABLE property_amenities
    ADD CONSTRAINT fk_proame_on_amenity FOREIGN KEY (amenity_id) REFERENCES amenities (id);

ALTER TABLE property_amenities
    ADD CONSTRAINT fk_proame_on_property FOREIGN KEY (property_id) REFERENCES properties (id);