CREATE TABLE property_rules
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id            BIGINT                                  NOT NULL,
    check_in_time          time WITHOUT TIME ZONE,
    check_out_time         time WITHOUT TIME ZONE,
    min_nights             INTEGER,
    max_nights             INTEGER,
    booking_lead_time_days INTEGER,
    CONSTRAINT pk_property_rules PRIMARY KEY (id)
);

ALTER TABLE property_rules
    ADD CONSTRAINT uc_property_rules_property UNIQUE (property_id);

ALTER TABLE property_rules
    ADD CONSTRAINT FK_PROPERTY_RULES_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);