CREATE TABLE IF NOT EXISTS property_change_logs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id BIGINT                                  NOT NULL,
    user_id     BIGINT,
    action      VARCHAR(255)                            NOT NULL,
    field_name  VARCHAR(255),
    old_value   VARCHAR(1000),
    new_value   VARCHAR(1000),
    changed_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_property_change_logs PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS seasonality_rules
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id    BIGINT                                  NOT NULL,
    start_date     date                                    NOT NULL,
    end_date       date                                    NOT NULL,
    price_modifier DECIMAL(5, 2)                           NOT NULL,
    day_of_week    VARCHAR(255),
    channel        VARCHAR(255),
    CONSTRAINT pk_seasonality_rules PRIMARY KEY (id)
);

ALTER TABLE seasonality_rules
    DROP CONSTRAINT IF EXISTS fk_seasonality_rules_on_property;

ALTER TABLE seasonality_rules
    ADD CONSTRAINT fk_seasonality_rules_on_property FOREIGN KEY (property_id) REFERENCES properties (id);
