-- Tabela principal de Rule Overrides
CREATE TABLE rule_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    min_nights_override INTEGER,
    CONSTRAINT pk_rule_overrides PRIMARY KEY (id),
    CONSTRAINT fk_rule_overrides_on_property FOREIGN KEY (property_id) REFERENCES properties (id)
);

-- Tabela de junção para dias de Check-in permitidos (ElementCollection)
CREATE TABLE rule_override_check_in_days (
    rule_override_id BIGINT NOT NULL,
    day_of_week VARCHAR(255) NOT NULL,
    CONSTRAINT fk_ro_check_in_on_override FOREIGN KEY (rule_override_id) REFERENCES rule_overrides (id)
);

-- Tabela de junção para dias de Check-out permitidos (ElementCollection)
CREATE TABLE rule_override_check_out_days (
    rule_override_id BIGINT NOT NULL,
    day_of_week VARCHAR(255) NOT NULL,
    CONSTRAINT fk_ro_check_out_on_override FOREIGN KEY (rule_override_id) REFERENCES rule_overrides (id)
);
