CREATE TABLE guest_profiles
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    internal_notes TEXT,
    CONSTRAINT pk_guest_profiles PRIMARY KEY (id),
    CONSTRAINT uc_guest_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_guest_profiles_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE guest_profile_tags
(
    guest_profile_id BIGINT       NOT NULL,
    tag              VARCHAR(255) NOT NULL,
    CONSTRAINT fk_guest_profile_tags_on_profile FOREIGN KEY (guest_profile_id) REFERENCES guest_profiles (id)
);

-- Tabela de auditoria para o Envers
CREATE TABLE guest_profiles_aud
(
    rev            INTEGER NOT NULL,
    revtype        SMALLINT,
    id             BIGINT  NOT NULL,
    user_id        BIGINT,
    internal_notes TEXT,
    CONSTRAINT pk_guest_profiles_aud PRIMARY KEY (rev, id),
    CONSTRAINT fk_guest_profiles_aud_on_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
