export const profileTokens = {
  ui: {
    theme: {
      bgLight: "#F0ECD9",
      bgDark: "#0A0D14",
      fgLight: "#0D0D0D",
      fgDark: "#E6E2D1",
      panelBgLight: "rgba(255,255,255,0.5)",
      panelBgDark: "rgba(255,255,255,0.02)",
      primaryAccent: "#e2621cff",
      pixelBlastDarkColor: "#4895ef",
    },
    social: {
      githubButtonClass: "bg-[#24292F] text-white hover:bg-[#24292F]/90 dark:bg-white dark:text-black dark:hover:bg-gray-200",
      googleBadgeClass: "bg-red-500/10 text-red-500 border-red-500/20",
      githubBadgeClass:
        "bg-slate-800/10 text-slate-800 border-slate-800/20 dark:bg-slate-200/10 dark:text-slate-200 dark:border-slate-200/20",
      googleBadgeHoverClass: "hover:bg-red-500 hover:text-white",
      githubBadgeHoverClass: "hover:bg-slate-800 hover:text-white dark:hover:bg-slate-200 dark:hover:text-black",
      googleButtonClass: "bg-white text-black hover:bg-gray-100",
    },
  },
  copy: {
    view: {
      loadingBrand: "Nexus ID",
      errorSessionExpiredTitle: "Sessão expirada.",
      errorNetworkTitle: "Backend indisponível.",
      errorGenericTitle: "Não foi possível carregar o perfil.",
      errorSessionExpiredSubtitle: "Faz login novamente para continuar.",
      errorNetworkSubtitle: "Verifica se o API Gateway e o user-service estão ligados.",
      errorGenericSubtitle: "Tenta novamente.",
      errorHttpPrefix: "HTTP ",
      errorJoiner: " · ",
      btnBack: "Voltar",
      btnGoToLogin: "Ir para Login",
      btnRetry: "Tentar Novamente",
      panelDataTitle: "Dados",
      panelDataSubtitle: "Informação carregada do backend",
      fieldEmail: "Email",
      fieldRole: "Role",
      fieldPhone: "Telefone",
      fieldId: "ID",
      dash: "-",
      panelRecoveryTitle: "Recuperação de Password",
      panelRecoverySubtitle: "Envia um link por email (fluxo real do backend)",
      btnSendEmail: "Enviar Email",
      panelContactTitle: "Atualizar Contacto",
      panelContactSubtitle: "Altera email e/ou telemóvel.",
      contactEmailLabel: "Email",
      contactPhoneLabel: "Telemóvel",
      contactSaveBtn: "Guardar",
      contactInvalidEmail: "Email inválido.",
      contactInvalidPhone: "Telemóvel inválido.",
      contactSaveOk: "Perfil atualizado.",
      contactSaveError: "Não foi possível atualizar o perfil.",
    },
    webhooksPanel: {
      title: "Webhooks",
      subtitle: "Recebe eventos do sistema no teu endpoint",
      targetUrlLabel: "Target URL",
      targetUrlPlaceholder: "https://example.com/webhooks/nexus",
      eventsLabel: "Eventos (CSV)",
      defaultEvents: "booking.created, booking.status.updated",
      btnCreate: "Criar",
      emptyState: "Sem webhooks configurados.",
      btnDisable: "Desativar",
      btnEnable: "Ativar",
      btnRemove: "Remover",
    },
    social: {
      title: "Contas Vinculadas",
      subtitle: "Faz login rapidamente utilizando os teus serviços favoritos",
      warningLine1:
        "Vincular uma conta permite que faças login no Nexus Estates sem precisares de inserir a tua password.",
      warningLine2: "Apenas teremos acesso ao teu email e nome público.",
      googleName: "Google",
      githubName: "GitHub",
      connectedFallback: "Vinculado",
      notConnected: "Não vinculado",
      processing: "A processar...",
      btnDisconnect: "Desvincular",
      btnConnectPrefix: "Conectar com ",
    },
    security: {
      panelTitle: "Segurança",
      panelSubtitle: "Protege a tua conta com uma credencial forte",
      updatedOk: "Password atualizada com sucesso.",
      updatedError: "Ocorreu um erro ao atualizar a password.",
      submitting: "A Processar...",
      submit: "Atualizar Segurança",
    },
    clerk: {
      title: "Contas Vinculadas",
      subtitle: "Liga Google, GitHub e Facebook via Clerk (OAuth)",
      notConfigured: "Clerk não configurado neste ambiente.",
      signedOutHint: "Para gerir as contas vinculadas, inicia sessão via Clerk com o provedor que queres ligar.",
    },
    webhooks: {
      secretCopied: "Secret copiado para o clipboard.",
      createFailed: "Falha ao criar webhook.",
    },
  },
} as const
